### ISSUE TITLE
Insecure MAC comparison

### ISSUE THREAD

**Issue by 197g** [zynaxsoft/smol_webhook#1]
You should not compare the MAC as a string, instead parse it from the header and compare it using the constant time comparison of `rust-crypto`.

> Using a plain == operator is not advised. A method like secure_compare performs a "constant time" string comparison, which renders it safe from certain timing attacks against regular equality operators.

[From: Githubs guide](https://developer.github.com/webhooks/securing/).

**Comment by zynaxsoft** [comment]
@HeroicKatora Thank you very much for the advice!

I just made a change for that in #2. What do you think?
